version: "3.9"
services:
  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway/.
    volumes:
      - .:/opt/app/gateway
    expose:
      - 8080
    environment:
      CLUSTER_SECRET: "6ycQElx60By2aG66YqQoAmMemebZoQgEBTsph2KkdW8="
      KNOWN_HOSTS: "img-proxy-worker-1"
      HTTP_PORT: 8080
    depends_on:
      - worker

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker/.
    volumes:
      - .:/opt/app/worker
    environment:
      CLUSTER_SECRET: "6ycQElx60By2aG66YqQoAmMemebZoQgEBTsph2KkdW8="
      HOST: "0.0.0.0"
      PORT: "8080"
      KNOWN_HOSTS: "img-proxy-worker-1"