global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "gateway"
    static_configs:
      - targets: [ "img-proxy-gateway-1:8080" ]
      - targets: [ "img-proxy-gateway-2:8080" ]
      - targets: [ "img-proxy-gateway-3:8080" ]

  - job_name: "worker"
    static_configs:
      - targets: [ "img-proxy-worker-1:8080" ]
      - targets: [ "img-proxy-worker-2:8080" ]
      - targets: [ "img-proxy-worker-3:8080" ]